### ISSUE TITLE
Uncaught Python exception: UnicodeDecodeError

### ISSUE THREAD

**Issue by OrianeK** [kjd/idna#119]
Hi,
  I am a high school student just starting to learn about testing techniques. I found a bug in the latest version (3.3) of idna while doing some fuzzing using  the fuzzing tool Atheris. The reproducing process is shown below:
````
Import idna
idna.encode(b'\x0a'+b'\x33'+b'\x81')
````
Is raising `UnicodeDecodeError`  with a traceback:
```
Detatails
Traceback (most recent call last):
  File "fuzzer_Idna.py", line 8, in TestOneInput
    idna.encode(data)
  File "/home/clou5/.local/lib/python3.8/site-packages/idna/core.py", line 342, in encode
    s = s.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 0: ordinal not in range(128)


```
My environment

```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import idna
>>> print(idna.__version__)
3.3
>>> 

```
There is a similar case previously fixed: #108

**Comment by kjd** [comment]
I agree its invalid input and should be throwing an exception, however the documentation states all IDNA errors will derive from the `IDNAError` class so we should catch it and re-raise it.

**Comment by OrianeK** [comment]
Thanks the bug confirmation. I'll try submitting a code patch for this bug.

**Comment by OrianeK** [comment]
Thanks for the bug confirmation. I'll try submitting a code patch for this bug.

**Comment by OrianeK** [comment]
@kjd  Thank you again checking this issue I added a pull request referring to previous solutions. The test was passed, if you have time would you mind taking a look for me? 
Thanks, 
https://github.com/kjd/idna/pull/120
