### ISSUE TITLE
Unable to encode/decode U+1F52B

### ISSUE THREAD

**Issue by alexkiro** [kjd/idna#19]
It seems that the U+1F52B PISTOL character added to Unicode in version 6.0 (2010) is not supported by the `idna` package:

```python
>>> idna.encode(u'\U0001f52b.test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chirila/env/local/lib/python2.7/site-packages/idna/core.py", line 354, in encode
    result.append(alabel(label))
  File "/home/chirila/env/local/lib/python2.7/site-packages/idna/core.py", line 275, in alabel
    check_label(label)
  File "/home/chirila/env/local/lib/python2.7/site-packages/idna/core.py", line 252, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+1F52B at position 1 of u'\U0001f52b' not allowed
>>> idna.decode('xn--bw8h.test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chirila/env/local/lib/python2.7/site-packages/idna/core.py", line 383, in decode
    result.append(ulabel(label))
  File "/home/chirila/env/local/lib/python2.7/site-packages/idna/core.py", line 302, in ulabel
    check_label(label)
  File "/home/chirila/env/local/lib/python2.7/site-packages/idna/core.py", line 252, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+1F52B at position 1 of u'\U0001f52b' not allowed
>>> 
```

While the python standard library can indeed encode/decode the codepoint:

```python
>>> u'\U0001f52b.test'.encode("idna")
'xn--bw8h.test'
>>> 'xn--bw8h.test'.decode("idna")
u'\U0001f52b.test'
```

**Comment by jribbens** [comment]
It is supported by the `idna` package, in that it correctly makes an error and refuses the character as per the IDNA standards. See http://unicode.org/cldr/utility/idna.jsp?a=%5CU0001F52B.com for example.

**Comment by kjd** [comment]
Emoji etc. are not allowed in domain names per the IDNA specification. Per RFC 5890, for example, "characters that are used to write text and that are not digits, symbols, or punctuation. Formally, they are characters with a Unicode General Category value starting in "L""
