### ISSUE TITLE
Multiple test failures when tests are run via unittest

### ISSUE THREAD

**Issue by mgorny** [kjd/idna#192]
When the test suite is run via unittest, a lot of regressions are reported in the 3.9 release:

```pytb
$ python -m unittest
................................................................sss.s............ss.s.....ssss.......sssssss..........................................................................................................................sssssss.......sssssss..sss...............................................................................................................................................s..ss.s..ssss................s..ss..ss..s...s.s..................................ssss.s.s..............................s.s...........ssss....ss...............s................................................................ss.s....................s...........................s......................................................ss......................................ss.sFF.F...F...F.F.......................................................................s.s.s...........................ss.s..........ss.............................................ssss.ss...............................ss.s.s........................................................s.s..ssss...ss...........ssss.ssss.............................................................................................................s.s......................s..s..................s.s........s.s................................................s.s.......ss.s.................................................................sss.s.ss.s.s...........................................................ss.s..s................................................................s.s.s..................s.................................s............................................................................ss...........s.........................................................................................................ss.s.......sss.s.s.s........s.s..........................ss.s.s....................s................s.......ssssssss...sssss...s..........................sss.s.ssssss.s................ss........................................ss.s..........................................................................................................s.......................................................................................................................ssss.s..........s..s.................s...............................................s...........s.s.s.........................................................sss.s.ss...............................................................s.s.s.........................................................ss.s...........................................................................................................................ss.s....ss...s.........ss.s.s.........................................................sssss.sssssFFFF..............ss..s.....................................................................................s...............................................sss.s.ss............ss.s.......................................................FF..............ss.s.s.s.....ssss.s.s....ss........................................................................................................................................s................ss.s......................................................s..s......sss...ss..........s.......................................................................sssss..F.F...Fsssssss.....sss.s................................ssssss.s.ssssssssss.ssss.......................................ss.....s.........................s.s.s...............................................................ss.s.s.....................................................................ss.s.............................................ssssss.s.sss..........ssssss......................................................s.s.........ss........................ss.s...................................F.F....F..............ssssss.....sss............s.......................s..........................s.s.............s.s...........................................s.............................................sss...ss.............ssss.sssssssss.s.sss.................s..................................................s.s....................s...................................................................s........................................................................................................................................sssss.sssss.ss..............F.sss..F.sss...s.............ssssss.s.sss.............................................................ss..F.ss..ss...s.s........................................................ss.s.s.......................................................................ssss....ss....ss...............................................................................s.......................................................................sss.ss.............sss.ss...ss........................................................................................................................sssss.ssssssssss..................................................................................................s......................................sss.s.sssss....sssss...................s.......s..........................................................ss..s...ssss...s.........................................................ss.s................................................................sssss.sssss...............s.s...s................sss...ss......ss.s.s......ssss.s............................................s................................................................s.s...........................................................................................................................................ss.......ss...s...........................................s.s.s.s....................s.s..sss.s..s............................................................................................................ss..s........F.F.F...FF.............................................................................ss..s....................ssss...ssssss.......................................................s...s.sss..s...........................................................................................................................
======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 860: 𞤥󠅮．ᡄႮ; 𞤥.ᡄႮ; [P1, V6]; xn--de6h.xn--mnd799a; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error 𞤥.ᡄႮ for '𞤥󠅮．ᡄႮ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 861: 𞤥󠅮.ᡄႮ; 𞤥.ᡄႮ; [P1, V6]; xn--de6h.xn--mnd799a; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error 𞤥.ᡄႮ for '𞤥󠅮.ᡄႮ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 863: 𞤃󠅮.ᡄႮ; 𞤥.ᡄႮ; [P1, V6]; xn--de6h.xn--mnd799a; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error 𞤥.ᡄႮ for '𞤃󠅮.ᡄႮ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 867: 𞤃.ᡄႮ; 𞤥.ᡄႮ; [P1, V6]; xn--de6h.xn--mnd799a; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error 𞤥.ᡄႮ for '𞤃.ᡄႮ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 871: 𞤃󠅮．ᡄႮ; 𞤥.ᡄႮ; [P1, V6]; xn--de6h.xn--mnd799a; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error 𞤥.ᡄႮ for '𞤃󠅮．ᡄႮ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 873: 𞤥.ᡄႮ; ; [P1, V6]; xn--de6h.xn--mnd799a; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error 𞤥.ᡄႮ for '𞤥.ᡄႮ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 2836: ꧐Ӏ᮪ࣶ．눵; ꧐Ӏ᮪ࣶ.눵; [P1, V6]; xn--d5a07sn4u297k.xn--2e1b; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error ꧐Ӏ᮪ࣶ.눵 for '꧐Ӏ᮪ࣶ．눵'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 2837: ꧐Ӏ᮪ࣶ．눵; ꧐Ӏ᮪ࣶ.눵; [P1, V6]; xn--d5a07sn4u297k.xn--2e1b; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error ꧐Ӏ᮪ࣶ.눵 for '꧐Ӏ᮪ࣶ．눵'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 2838: ꧐Ӏ᮪ࣶ.눵; ; [P1, V6]; xn--d5a07sn4u297k.xn--2e1b; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error ꧐Ӏ᮪ࣶ.눵 for '꧐Ӏ᮪ࣶ.눵'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 2839: ꧐Ӏ᮪ࣶ.눵; ꧐Ӏ᮪ࣶ.눵; [P1, V6]; xn--d5a07sn4u297k.xn--2e1b; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error ꧐Ӏ᮪ࣶ.눵 for '꧐Ӏ᮪ࣶ.눵'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 3071: ڹ．ᡳᅟ; ڹ.ᡳᅟ; [P1, V6]; xn--skb.xn--osd737a; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error ڹ.ᡳᅟ for 'ڹ．ᡳᅟ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 3072: ڹ.ᡳᅟ; ; [P1, V6]; xn--skb.xn--osd737a; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error ڹ.ᡳᅟ for 'ڹ.ᡳᅟ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 3432: Ⴚ.Σ; Ⴚ.σ; [P1, V6]; xn--ynd.xn--4xa; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error Ⴚ.σ for 'Ⴚ.Σ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 3434: Ⴚ.ς; ; [P1, V6]; xn--ynd.xn--3xa; ; xn--ynd.xn--4xa; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error Ⴚ.ς for 'Ⴚ.ς'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 3438: Ⴚ.σ; ; [P1, V6]; xn--ynd.xn--4xa; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error Ⴚ.σ for 'Ⴚ.σ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 3935: ςჅ。ݚ; ςჅ.ݚ; [P1, V6]; xn--3xa677d.xn--epb; ; xn--4xa477d.xn--epb; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error ςჅ.ݚ for 'ςჅ。ݚ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 3937: ΣჅ。ݚ; σჅ.ݚ; [P1, V6]; xn--4xa477d.xn--epb; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error σჅ.ݚ for 'ΣჅ。ݚ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 3942: ΣჅ.ݚ; σჅ.ݚ; [P1, V6]; xn--4xa477d.xn--epb; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error σჅ.ݚ for 'ΣჅ.ݚ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 4507: Ⴖͦ.; ; [P1, V6]; xn--hva929d.; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error Ⴖͦ. for 'Ⴖͦ.'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 4514: ࢻ.Ⴃ𞀒; ; [P1, V6]; xn--hzb.xn--bnd2938u; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error ࢻ.Ⴃ𞀒 for 'ࢻ.Ⴃ𞀒'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 4613: 攌꯭.ᢖ-Ⴘ; ; [P1, V6]; xn--p9ut19m.xn----k1g451d; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error 攌꯭.ᢖ-Ⴘ for '攌꯭.ᢖ-Ⴘ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 6028: ჁႱ6̘。ßᬃ; ჁႱ6̘.ßᬃ; [P1, V6]; xn--6-8cb555h2b.xn--zca894k; ; xn--6-8cb555h2b.xn--ss-2vq; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error ჁႱ6̘.ßᬃ for 'ჁႱ6̘。ßᬃ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 6030: ჁႱ6̘。SSᬃ; ჁႱ6̘.ssᬃ; [P1, V6]; xn--6-8cb555h2b.xn--ss-2vq; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error ჁႱ6̘.ssᬃ for 'ჁႱ6̘。SSᬃ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 6032: Ⴡⴑ6̘。Ssᬃ; Ⴡⴑ6̘.ssᬃ; [P1, V6]; xn--6-8cb306hms1a.xn--ss-2vq; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error Ⴡⴑ6̘.ssᬃ for 'Ⴡⴑ6̘。Ssᬃ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 6036: ჁႱ6̘.SSᬃ; ჁႱ6̘.ssᬃ; [P1, V6]; xn--6-8cb555h2b.xn--ss-2vq; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error ჁႱ6̘.ssᬃ for 'ჁႱ6̘.SSᬃ'

======================================================================
FAIL: runTest (tests.test_idna_uts46.TestIdnaTest)
IdnaTestV2.txt line 6037: Ⴡⴑ6̘.Ssᬃ; Ⴡⴑ6̘.ssᬃ; [P1, V6]; xn--6-8cb306hms1a.xn--ss-2vq; ; ; 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/idna/tests/test_idna_uts46.py", line 182, in runTest
    self.fail("decode() did not emit required error {} for {}".format(to_unicode, repr(source)))
AssertionError: decode() did not emit required error Ⴡⴑ6̘.ssᬃ for 'Ⴡⴑ6̘.Ssᬃ'

----------------------------------------------------------------------
Ran 6256 tests in 0.693s

FAILED (failures=26, skipped=562)
```

FWICS CI is using pytest instead, but pytest seems to run only a very small portion of the test suite (6256 tests via unittest, 32 tests via pytest).

**Comment by kjd** [comment]
Thanks, I overlooked there was a change to the UTS46 algorithm in Unicode 16.0.0, which I think is the cause of this. I don't think it will materially impact real-world conversions but will fix.

**Comment by kjd** [comment]
Version 3.10 has been released which should test cleanly. It doesn't resolve the underlying issue but means this won't exhibit on the current version.

**Comment by mgorny** [comment]
Thanks!

**Comment by kjd** [comment]
Replaced with issue #196 as this issue is resolved.
