### ISSUE TITLE
Length checks don't work and lead to funky errors

### ISSUE THREAD

**Issue by hynek** [kjd/idna#36]
Hi,

observe:

```pycon
>>> idna.encode("x" * 65)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/idna/core.py", line 355, in encode
    result.append(alabel(label))
  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/idna/core.py", line 276, in alabel
    check_label(label)
  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/idna/core.py", line 253, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+0027 at position 2 of "b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'" not allowed
Codepoint U+0027 at position 2 of "b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'" not allowed
```

The problem are the following [lines](https://github.com/kjd/idna/blob/master/idna/core.py#L266-L270).

You check the length of the label and you *do* raise an `IDNAError('Label too long')`, however there’s an `except UnicodeError:` and `IDNAError` happens to be a subclass of `UnicodeError`.  I that’s where I closed my pdb session. :)

**Comment by kjd** [comment]
Good catch, thanks. Will fix.
