### ISSUE TITLE
Misleading error message: Codepoint U+0027 at position 2 of "b'foo bar'" not allowed

### ISSUE THREAD

**Issue by joernheissler** [kjd/idna#42]
I accidentally passed a name with a blank to idna.encode; It seems to encode it to bytes and then complains about the apostrophe of b'foo bar'.
Python2 correctly complains: `idna.core.InvalidCodepoint: Codepoint U+0020 at position 4 of u'foo bar' not allowed`

Test case:
```
import idna
idna.encode('foo bar')
```

Result:
```
$ python3 foo.py
Traceback (most recent call last):
  File "foo.py", line 2, in <module>
    idna.encode('foo bar')
  File "/home/joern/env/lib/python3.5/site-packages/idna/core.py", line 355, in encode
    result.append(alabel(label))
  File "/home/joern/env/lib/python3.5/site-packages/idna/core.py", line 276, in alabel
    check_label(label)
  File "/home/joern/env/lib/python3.5/site-packages/idna/core.py", line 253, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+0027 at position 2 of "b'foo bar'" not allowed
```

**Comment by jribbens** [comment]
It looks like it's because the `except UnicodeError` on line 269 of `core.py` is intended to be catching only exceptions from line 261 `label = label.encode('ascii')` but is also catching the perfectly good error message `idna.core.InvalidCodepoint: Codepoint U+0020 at position 4 of 'foo bar' not allowed` that is being thrown by `ulabel` because `InvalidCodepoint` is an indirect subclass of `UnicodeError`.

This bug is therefore already fixed by ebefacd3134d0f5da4745878620a6a1cba86d130 which made `IDNAError` not be a subclass of `UnicodeError` anymore.

**Comment by kjd** [comment]
Thanks for taking a look @jribbens !

**Comment by joernheissler** [comment]
Okay, so I tried the latest version.

```
$ python3 foo.py
Traceback (most recent call last):
  File "/home/joern/idna/lib/python3.5/site-packages/idna-2.2-py3.5.egg/idna/core.py", line 263, in alabel
  File "/home/joern/idna/lib/python3.5/site-packages/idna-2.2-py3.5.egg/idna/core.py", line 299, in ulabel
  File "/home/joern/idna/lib/python3.5/site-packages/idna-2.2-py3.5.egg/idna/core.py", line 253, in check_label
idna.core.InvalidCodepoint: Codepoint U+0020 at position 4 of 'foo bar' not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 2, in <module>
    idna.encode(b'foo bar')
  File "/home/joern/idna/lib/python3.5/site-packages/idna-2.2-py3.5.egg/idna/core.py", line 355, in encode
  File "/home/joern/idna/lib/python3.5/site-packages/idna-2.2-py3.5.egg/idna/core.py", line 265, in alabel
idna.core.IDNAError: The label b'foo bar' is not a valid A-label
```

The "good" exception is now visible. But what's with the second? :)

**Comment by jribbens** [comment]
It's the appalling way Python 3 reports exceptions. `ulabel` throws the first exception listed above, which is caught by line 264 in `alabel` and the second exception is thrown. Both of them appear correct and I don't think this behaviour is a problem.

**Comment by joernheissler** [comment]
In that case, everything appears to be in order now. Thank you!
