### ISSUE TITLE
`uts46_remap` usage of 'std3_rules` is inverted

### ISSUE THREAD

**Issue by Arachnid** [kjd/idna#54]
AIUI, when `std3_rules` is True, invalid characters for a domain should be rejected. Instead, `uts46_remap` allows them unless `std3_rules` is False.

**Comment by kjd** [comment]
Yep, looks like a bug:

```
>>> idna.uts46_remap('A_', std3_rules=True)
'a_'
>>> idna.uts46_remap('A_', std3_rules=False)
Traceback (most recent call last):
  File "idna/core.py", line 327, in uts46_remap
    raise IndexError()
IndexError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "idna/core.py", line 332, in uts46_remap
    _unot(code_point), pos + 1, repr(domain)))
idna.core.InvalidCodepoint: Codepoint U+005F not allowed at position 2 in 'A_'
>>>
```
