### ISSUE TITLE
New package py_0 breaks conda update 

### ISSUE THREAD

**Issue by dhuebner** [kjd/idna#55]
| noarch/idna-2.6-py_0.tar.bz2

From https://anaconda.org/conda-forge/idna/files

Breaks `conda update conda`

```
Package plan for installation in environment /opt/conda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0         1017 B  conda-forge
    libffi-3.2.1               |                3          47 KB  conda-forge
    asn1crypto-0.22.0          |           py35_0         149 KB  conda-forge
    certifi-2017.7.27.1        |           py35_0         204 KB  conda-forge
    chardet-3.0.4              |           py35_0         189 KB  conda-forge
    idna-2.6                   |             py_0          47 KB  conda-forge
    pycparser-2.18             |           py35_0         169 KB  conda-forge
    pysocks-1.6.7              |           py35_0          21 KB  conda-forge
    cffi-1.10.0                |           py35_0         388 KB  conda-forge
    cryptography-2.0.3         |           py35_0         853 KB  conda-forge
    pyopenssl-17.2.0           |           py35_0          77 KB  conda-forge
    urllib3-1.22               |           py35_0         155 KB  conda-forge
    requests-2.18.4            |           py35_1          91 KB  conda-forge
    conda-4.3.24               |           py35_0         514 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.8 MB

The following NEW packages will be INSTALLED:

    asn1crypto:   0.22.0-py35_0      conda-forge
    certifi:      2017.7.27.1-py35_0 conda-forge
    cffi:         1.10.0-py35_0      conda-forge
    chardet:      3.0.4-py35_0       conda-forge
    cryptography: 2.0.3-py35_0       conda-forge
    idna:         2.6-py_0           conda-forge
    libffi:       3.2.1-3            conda-forge
    pycparser:    2.18-py35_0        conda-forge
    pyopenssl:    17.2.0-py35_0      conda-forge
    pysocks:      1.6.7-py35_0       conda-forge
    urllib3:      1.22-py35_0        conda-forge

The following packages will be UPDATED:

    conda:        4.1.11-py35_0                  --> 4.3.24-py35_0 conda-forge
    conda-env:    2.5.2-py35_0                   --> 2.6.0-0       conda-forge
    requests:     2.10.0-py35_0                  --> 2.18.4-py35_1 conda-forge

[91mTraceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/conda/exceptions.py", line 634, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/conda/cli/main.py", line 114, in _main
    imported = importlib.import_module(module)
  File "/opt/conda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/conda/lib/python3.5/site-packages/conda/cli/main_update.py", line 10, in <module>
    from .install import install
  File "/opt/conda/lib/python3.5/site-packages/conda/cli/install.py", line 20, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "/opt/conda/lib/python3.5/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/opt/conda/lib/python3.5/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/opt/conda/lib/python3.5/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/opt/conda/lib/python3.5/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "/opt/conda/lib/python3.5/site-packages/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/opt/conda/lib/python3.5/site-packages/requests/packages.py", line 7, in <module>
    locals()[package] = __import__(package)
ImportError: No module named 'idna'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/opt/conda/lib/python3.5/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/opt/conda/lib/python3.5/site-packages/conda/exceptions.py", line 638, in conda_exception_handler
    return handle_exception(e)
  File "/opt/conda/lib/python3.5/site-packages/conda/exceptions.py", line 628, in handle_exception
    print_unexpected_error_message(e)
  File "/opt/conda/lib/python3.5/site-packages/conda/exceptions.py", line 590, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/opt/conda/lib/python3.5/site-packages/conda/cli/main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "/opt/conda/lib/python3.5/site-packages/conda/connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "/opt/conda/lib/python3.5/site-packages/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/opt/conda/lib/python3.5/site-packages/requests/packages.py", line 7, in <module>
    locals()[package] = __import__(package)
ImportError: No module named 'idna'
```

**Comment by kjd** [comment]
I'm not really sure what we're to do here. Seems to be a problem with the downstream packaging and not an issue with this library.

**Comment by dhuebner** [comment]
@kjd Just remove the no arch package from the conda repository:

46.8 kB | \| noarch/idna-2.6-py_0.tar.bz2 | 13 days and 3 hours ago | conda-forge | 11756
-- | -- | -- | -- | --

**Comment by kjd** [comment]
I didn't place it there, I can only assume they are repackaging it from PyPI.
