### ISSUE TITLE
IndexError instead of IDNAError

### ISSUE THREAD

**Issue by suola** [kjd/idna#68]
I get `IndexError` instead of `idna.core.IDNAError` - if I understood correctly this is not what should happen:

```python
>>> import idna
>>> idna.decode('xn--eckwd4c7c.xn--zckzah')
'ドメイン.テスト'
>>> idna.decode('xn--eckwd4c7c.xn--zckzah ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/encodings/punycode.py", line 207, in decode
    res = punycode_decode(input, errors)
  File "/usr/local/lib/python3.6/encodings/punycode.py", line 194, in punycode_decode
    return insertion_sort(base, extended, errors)
  File "/usr/local/lib/python3.6/encodings/punycode.py", line 165, in insertion_sort
    bias, errors)
  File "/usr/local/lib/python3.6/encodings/punycode.py", line 146, in decode_generalized_number
    % extended[extpos])
IndexError: string index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/idna/core.py", line 389, in decode
    s = ulabel(label)
  File "/usr/local/lib/python3.6/site-packages/idna/core.py", line 307, in ulabel
    label = label.decode('punycode')
IndexError: decoding with 'punycode' codec failed (IndexError: string index out of range)
```

**Comment by jrlevine** [comment]
That's definitely wrong, but it's not clear what the right answer is. libidn2 ignores the space and returns the Japanese string, 
The error is in the existing punycode library, since this fails too:
`b'xn--eckwd4c7c.xn--zckzah '.decode('idna')`

**Comment by smbl64** [comment]
I believe there is a bug in Python's `punycode` module. 
This code [`extended[extpos]`](https://github.com/python/cpython/blob/86900a49000c4a96ad1dc34e49d8af4245b08843/Lib/encodings/punycode.py#L146) is wrong and should be `extended[extpos-1]`.

**Comment by kjd** [comment]
Fixed upstream. Closing.
