### ISSUE TITLE
IndexError with new trailing hyphen check

### ISSUE THREAD

**Issue by john-kurkowski** [kjd/idna#82]
#64 introduced the following uncaught exception. Is this intended?

```python
>>> idna.ulabel('xn--')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/John/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/idna/core.py", line 303, in ulabel
    if label.decode('ascii')[-1] == '-':
IndexError: string index out of range
```

I would've expected `UnicodeError` or `IDNAError`, which are more descriptive.

**Comment by john-kurkowski** [comment]
If this is indeed an error. `check_label` seems to confirm it would be, if processing continued with an empty string:

```python
>>> idna.check_label('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/John/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/idna/core.py", line 239, in check_label
    raise IDNAError('Empty Label')
idna.core.IDNAError: Empty Label
```

**Comment by kjd** [comment]
It is a malformed label and thus should throw an exception, but you're correct that `IndexError` is the wrong exception for this. Have created a patch that throws `IDNAError` instead.
